[package]
name = "expr-parser-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
thiserror = "1.0.38"
unicode-xid = "0.2.4"

[dev-dependencies]
test-case = "2.2.2"
