[package]
name = "expr-parser"
version = "0.1.0"
edition = "2021"
authors = ["emily Crandall Fleischman <emilycf@mit.edu>"]
license = "MIT"

[dependencies]
derivative = "2.2.0"
itertools = "0.10.5"
thiserror = "1.0.38"
unicode-xid = "0.2.4"

[dev-dependencies]
anyhow = "1.0.68"
test-case = "2.2.2"
